services:
  mysql:
    container_name: 'mysql-temp'
    image: 'mysql:8.0.44'
    environment:
      - 'MYSQL_DATABASE=userdb'
      - 'MYSQL_PASSWORD=123'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=user1'
    ports:
      - '3306:3306'
    volumes:
        - mysql-login:/var/lib/mysql'
    networks:
      - app-network
  backend:
    container_name: 'springboot-temp'
    image: 'springboot-temp:tmp'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/userdb'
        - 'SPRING_DATASOURCE_USERNAME=root'
        - 'SPRING_DATASOURCE_PASSWORD=123'
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    networks:
      - app-network
volumes:
  mysql-login:

networks:
  app-network:
    driver: bridge
